### ISSUE TITLE
get_cdrs returns forbidden

### ISSUE THREAD

**Issue by visiblethinking** [tnewman/PyKazoo#34]
>>> client.cdrs.get_cdrs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pykazoo/cdrs.py", line 20, in get_cdrs
    return self.rest_request.get('cdrs', filters)
  File "/usr/local/lib/python3.8/site-packages/pykazoo/restrequest.py", line 38, in get
    return self._request('GET', action, None, params, content_type)
  File "/usr/local/lib/python3.8/site-packages/pykazoo/restrequest.py", line 131, in _request
    raise RuntimeError(message)
RuntimeError: Error Code: 403 Data: b'{"version":"5.0.57","timestamp":"2021-06-04T21:07:45Z","node":"dqZFtHthbelyE8MI6vU-LA","request_id":"6a7821581099d43be41d85dd36489ffa","tokens":{"consumed":1,"remaining":100},"auth_token":"XXX","data":{"message":"forbidden"},"error":"403","message":"forbidden","status":"error"}'

**Comment by tnewman** [comment]
Hello, I stopped working on this project a long time ago after I lost interest; however, I am open to either pull requests or appointing a new maintainer. Please open a PR or a separate issue to discuss either of these options.
